# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowjs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowfilechunk',
            name='parent',
        ),
        migrations.DeleteModel(
            name='FlowFile',
        ),
        migrations.DeleteModel(
            name='FlowFileChunk',
        ),
    ]
