# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_datastore_model', '0020_auto_20160121_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachment_custom_field_config',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='chosen_data_form_config',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='data_point_classification',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='flowfile',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='custom_field_config',
        ),
        migrations.AlterUniqueTogether(
            name='datapointclassification',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='data_form_config',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='l0',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='l0_permitted_projects',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='l1',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='l2',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='l3',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='l4',
        ),
        migrations.RemoveField(
            model_name='datapointclassification',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='datapointclassificationpermission',
            name='data_point_classification',
        ),
        migrations.RemoveField(
            model_name='datapointclassificationpermission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='query',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.DeleteModel(
            name='DataPointClassification',
        ),
        migrations.DeleteModel(
            name='DataPointClassificationPermission',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
