# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_chembl_model_extension', '0034_auto_20160405_0459'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='bigimage',
            field=models.TextField(default=b'', help_text=b'A larger base64 encoded image for the compound, for use in the front end'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='blinded_batch_id',
            field=models.CharField(blank=True, default=b'', help_text=b'UUID assigned in cases where the compound batch is an inventory item or a molecule without a structure', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='canonical_smiles',
            field=models.TextField(blank=True, default=None, help_text=b'Canonical SMILES pattern for the uploaded compound batch generated by the pybel library from openbabel', null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default=None, help_text=b'The display name for the user who created this compound batch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='created_by_id',
            field=models.IntegerField(blank=True, default=None, help_text=b'The ID from the user who created this compound batch', null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='ctab',
            field=models.TextField(blank=True, default=None, help_text=b'The raw MDL molfile text (chemical table block - ctab) that was used to generate this compound batch', null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='custom_fields',
            field=django_hstore.fields.DictionaryField(help_text=b'The main field where data associated with the molecule is stored - data may be strings, numbers, lists or objects'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='image',
            field=models.TextField(default=b'', help_text=b'A small base64 encoded image for the compound, for use in the front end'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='multiple_batch_id',
            field=models.IntegerField(default=0, help_text=b'The multiple batch id of this molecule and any others that were created at the same time'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='original_smiles',
            field=models.TextField(blank=True, default=None, help_text=b'The SMILES pattern that was originally uploaded', null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='project',
            field=models.ForeignKey(blank=True, default=None, help_text=b'Foreign key to the projects table, used to determine permissions on the compound batch object', null=True, on_delete=django.db.models.deletion.CASCADE, to='cbh_core_model.Project'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='project_counter',
            field=models.IntegerField(blank=True, default=-1, help_text=b'ID for this compound batch within the context of the project', null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='properties',
            field=django_hstore.fields.DictionaryField(help_text=b'System generated properties for the molecule and whether it is archived'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='related_molregno',
            field=models.ForeignKey(blank=True, default=None, help_text=b'The foreign key relationship to the MoleculeDictionary record generated for this compound. May be null for compounds without a structure or inventory items', null=True, on_delete=django.db.models.deletion.CASCADE, to='chembl_business_model.MoleculeDictionary'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='standard_inchi',
            field=models.TextField(blank=True, default=None, help_text=b'The standard Inchi string for the molecule as generated by the standard Inchi library', null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='standard_inchi_key',
            field=models.CharField(blank=True, default=None, help_text=b'The standard Inchi key string for the molecule as generated by the standard Inchi library', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='std_ctab',
            field=models.TextField(blank=True, default=None, help_text=b'The standardised version of the above ctab/molfile text standardised using the Inchi software', null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='uncurated_fields',
            field=django_hstore.fields.DictionaryField(help_text=b'The fields that were uploaded to the record but were not mapped on to anything, or extra information that the user wanted to include'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundbatch',
            name='warnings',
            field=django_hstore.fields.DictionaryField(help_text=b'Warnings that were raised when the molecule was uploaded'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundmultiplebatch',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default=None, help_text=b'User who created this multiple batch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cbhcompoundmultiplebatch',
            name='project',
            field=models.ForeignKey(blank=True, default=None, help_text=b'Project that the multiple batch was created in', null=True, on_delete=django.db.models.deletion.CASCADE, to='cbh_core_model.Project'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundmultiplebatch',
            name='saved',
            field=models.BooleanField(default=False, help_text=b'Whether this multiple batch has been saved or not'),
        ),
        migrations.AlterField(
            model_name='cbhcompoundmultiplebatch',
            name='uploaded_data',
            field=picklefield.fields.PickledObjectField(editable=False, help_text=b'Now used to store the headers from the file used to generate the multiple batch, picke use perhaps can be improved or is deprecated'),
        ),
    ]
