# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0045_project_project_counter_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbhflowfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text=b'Date the upload was created'),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='identifier',
            field=models.SlugField(help_text=b'String identifier built using the name and session id of the file for security so other sessions cannot access the file', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='original_filename',
            field=models.CharField(help_text=b'The original filename of the file', max_length=200),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='project',
            field=models.ForeignKey(help_text=b'Project that the uploaded file is associated with', on_delete=django.db.models.deletion.CASCADE, to='cbh_core_model.Project'),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='state',
            field=models.IntegerField(choices=[(1, b'Uploading'), (2, b'Completed'), (3, b'Upload Error')], default=1, help_text=b'Current status of the upload'),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='total_chunks',
            field=models.IntegerField(default=0, help_text=b'Number of chunks the file was split up into to upload'),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='total_chunks_uploaded',
            field=models.IntegerField(default=0, help_text=b'Number of chunks uploaded so far'),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='total_size',
            field=models.IntegerField(default=0, help_text=b'Size in bytes'),
        ),
        migrations.AlterField(
            model_name='cbhflowfile',
            name='updated',
            field=models.DateField(auto_now=True, help_text=b'Date the upload was updated'),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='allowed_values',
            field=models.CharField(blank=True, default=b'', help_text=b'What values are allowed for this field', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='attachment_field_mapped_to',
            field=models.ForeignKey(blank=True, default=None, help_text=b'deprecated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_field_mapped_from', to='cbh_core_model.PinnedCustomField'),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='custom_field_config',
            field=models.ForeignKey(blank=True, default=None, help_text=b'the custom field config object this field is part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_custom_field', to='cbh_core_model.CustomFieldConfig'),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='default',
            field=models.CharField(blank=True, default=b'', help_text=b'The default value of this field to be applied when adding data via the angular schema form', max_length=500),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='description',
            field=models.CharField(blank=True, default=b'', help_text=b'Description of the field to be displayed in the angular schema form when editing data', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='field_key',
            field=models.CharField(default=b'', help_text=b'field key value, not currently used perhaps deprecated', max_length=500),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='field_type',
            field=models.CharField(choices=[(b'text', b'Short text field'), (b'char', b'Short text field'), (b'textarea', b'Full text'), (b'uiselect', b'Choice field'), (b'integer', b'Integer field'), (b'number', b'Decimal field'), (b'uiselecttag', b'Choice allowing create'), (b'uiselecttags', b'Tags field allowing create'), (b'percentage', b'Percentage field'), (b'radios', b'Radio buttons'), (b'date', b'Date Field'), (b'href', b'Link to server or external'), (b'imghref', b'Image link to embed'), (b'decimal', b'Decimal field'), (b'boolean', b'checkbox'), (b'related', b'TEST'), (b'file', b'File Upload')], default=b'char', help_text=b'The data type of the data to be added in the front end forms for this field', max_length=15),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='name',
            field=models.CharField(help_text=b'Name of the field in the project, may contain any character apart from slashes and dots', max_length=500),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='open_or_restricted',
            field=models.CharField(choices=[(b'open', b'Open to all viewers'), (b'restricted', b'Restricted to editors')], default=b'open', help_text=b'Whether to open up this field to people who only have viewer rights on the project', max_length=20),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='part_of_blinded_key',
            field=models.BooleanField(default=False, help_text=b'deprecated unused field', verbose_name=b'blind key'),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='pinned_for_datatype',
            field=models.ForeignKey(blank=True, default=None, help_text=b'deprecated', null=True, on_delete=django.db.models.deletion.CASCADE, to='cbh_core_model.DataType'),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='position',
            field=models.PositiveSmallIntegerField(help_text=b'Auto-filled field that says what order the fields in a custom field config should be displayed int he form'),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='required',
            field=models.BooleanField(default=False, help_text=b'Whetehr the field is required'),
        ),
        migrations.AlterField(
            model_name='pinnedcustomfield',
            name='standardised_alias',
            field=models.ForeignKey(blank=True, default=None, help_text=b'deprecated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_mapped_from', to='cbh_core_model.PinnedCustomField'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text=b'User who created the project', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom_field_config',
            field=models.ForeignKey(blank=True, default=None, help_text=b'Custom field config object which is linked to this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='cbh_core_model.CustomFieldConfig'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enabled_forms',
            field=models.ManyToManyField(blank=True, help_text=b'deprecated field not used for anything', to='cbh_core_model.DataFormConfig'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_default',
            field=models.BooleanField(default=False, help_text=b'deprecated field not used for anythign'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, help_text=b'What would you like to call your project', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_counter_start',
            field=models.IntegerField(default=1, help_text=b'start of the incremental ID field for this project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_key',
            field=models.SlugField(blank=True, default=None, help_text=b'key for the project, mostly deprecated in favour of id now but still used in some places', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, default=None, help_text=b'Project type that this project is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, to='cbh_core_model.ProjectType'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='custom_field_config_template_id',
            field=models.IntegerField(blank=True, default=None, help_text=b'If you wish for this project type to include a set of default fields, find an appropriate custom field config ID to use as a template and add it here', null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, help_text=b'Name of the project type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='plate_map_project_type',
            field=models.BooleanField(default=False, help_text=b'Whether this project type is for plate maps'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='saved_search_project_type',
            field=models.BooleanField(default=False, help_text=b'Whether this project type is to be used in saved searches'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='set_as_default',
            field=models.BooleanField(default=False, help_text=b'Whether this project type should be used as the default project type on the system, set back to false if another project type is set as default'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='show_compounds',
            field=models.BooleanField(default=True, help_text=b'Whether this project type should show compounds'),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='data_manager_email',
            field=models.CharField(default=b'', help_text=b'Email address for support requests', max_length=100),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='data_manager_name',
            field=models.CharField(default=b'', help_text=b'Name of support requests manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='enable_smiles_input',
            field=models.NullBooleanField(default=True, help_text=b'Whether the SMILES input field should be enabled when adding multiple compounds'),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='file_errors_from_backend',
            field=models.NullBooleanField(default=False, help_text=b'Whether the error message on file upload should be the exception message from the back end'),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='instance_alias',
            field=models.CharField(default=b'ChemiReg', help_text=b'What the instance of ChemBio Hub should be labelled as (not really used, deprecated', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='project_alias',
            field=models.CharField(default=b'project', help_text=b'What projects on the system should be called (not really used, could be deprecated)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='result_alias',
            field=models.CharField(default=b'result', help_text=b'What search results on the system should be called (not really used, could be deprecated)', max_length=50, null=True),
        ),
    ]
