# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 08:03
from __future__ import unicode_literals

from django.db import migrations

def update_index_mapppings(apps, stuff):

    Project = apps.get_model("cbh_core_model", "Project")
    from cbh_core_api.resources import create_or_update_project_index

    for proj_id in Project.objects.values_list("id", flat=True):
        create_or_update_project_index(proj_id)
        print ("successfully created index for project %d" % proj_id)


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0048_auto_20160516_1204'),
    ]

    operations = [
        migrations.RunPython(update_index_mapppings)
    ]
