# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0049_auto_20160526_0303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataformconfig',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dataformconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dataformconfig',
            name='l0',
        ),
        migrations.RemoveField(
            model_name='dataformconfig',
            name='l1',
        ),
        migrations.RemoveField(
            model_name='dataformconfig',
            name='l2',
        ),
        migrations.RemoveField(
            model_name='dataformconfig',
            name='l3',
        ),
        migrations.RemoveField(
            model_name='dataformconfig',
            name='l4',
        ),
        migrations.RemoveField(
            model_name='dataformconfig',
            name='parent',
        ),
        migrations.DeleteModel(
            name='DataFormConfig',
        ),
    ]
