# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0049_auto_20160526_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinningconfig',
            name='enable_add_multiple',
            field=models.NullBooleanField(default=True, help_text=b'Enabling the upload of multiple items'),
        ),
        migrations.AddField(
            model_name='skinningconfig',
            name='enable_supplementary_data',
            field=models.NullBooleanField(default=True, help_text=b'Enabling the upload of supplementary data'),
        ),
        migrations.AddField(
            model_name='skinningconfig',
            name='login_page_subtitle',
            field=models.CharField(default=b'Home of ChemiReg, InvReg and AssayReg', help_text=b'Text to use as the login page subtitle', max_length=300),
        ),
        migrations.AddField(
            model_name='skinningconfig',
            name='login_page_title',
            field=models.CharField(default=b'Welcome to ChemBio Hub Platform', help_text=b'Text to use as the login page title', max_length=300),
        ),
    ]
