# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0050_auto_20160609_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbhflowfile',
            name='identifier',
            field=models.SlugField(help_text=b'String identifier built using the name and session id of the file for security so other sessions cannot access the file', max_length=1024, unique=True),
        ),
    ]
