# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0051_auto_20160610_0108'),
        ('cbh_core_model', '0050_auto_20160601_0948'),
    ]

    operations = [
    ]
