# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 23:06
from __future__ import unicode_literals

from django.db import migrations

def create_cfc(apps, d):
    User = apps.get_model("auth", "user")
    u = User.objects.create(username="default")
    CustomFieldConfig = apps.get_model("cbh_core_model", "CustomFieldConfig")
    c = CustomFieldConfig.objects.create(name="default CFC", created_by=u)
    PinnedCustomField = apps.get_model("cbh_core_model", "PinnedCustomField")
    pcf = PinnedCustomField.objects.create(name="foo", custom_field_config=c, position=1)

    c = CustomFieldConfig.objects.create(name="default CFC2", created_by=u)
    pcf = PinnedCustomField.objects.create(name="foo", custom_field_config=c, position=1)

class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0053_auto_20160613_0500'),
    ]

    operations = [
        migrations.RunPython(create_cfc),
    ]

    